# Generated by Django 5.1.7 on 2025-03-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_service_trainer_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='available_time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service'),
        ),
    ]
