# Generated by Django 5.1.7 on 2025-03-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trainer_available_time_slots_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
