# Generated by Django 5.1.7 on 2025-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_package_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_in_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
