# Generated by Django 5.1.7 on 2025-03-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_booking_package_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
