# Generated by Django 5.1.7 on 2025-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_trainer_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('Weight Gain', 'Weight Gain'), ('Weight Loss', 'Weight Loss'), ('Self Defense', 'Self Defense'), ('Strength', 'Strength')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Amateur', 'Amateur'), ('Expert', 'Expert')], max_length=10, null=True),
        ),
    ]
