# Generated by Django 5.1.7 on 2025-03-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(default='morning', max_length=20),
        ),
    ]
