# Generated by Django 5.1.7 on 2025-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='booked_time_slots',
            field=models.JSONField(default=None),
        ),
    ]
