# Generated by Django 5.1.7 on 2025-03-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
