# Generated by Django 5.1.7 on 2025-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='available_time_slots',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='booked_time_slots',
            field=models.JSONField(default=list),
        ),
    ]
