# Generated by Django 5.1.7 on 2025-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_trainer_available_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='available_time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='booked_time_slots',
            field=models.JSONField(default=None),
        ),
    ]
