# Generated by Django 5.1.4 on 2025-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_trainer_available_time_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
