# Generated by Django 5.1.4 on 2025-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_trainer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('Weight Gain', 'Weight Gain'), ('Weight Loss', 'Weight Loss'), ('Self Defense', 'Self Defense'), ('Strength', 'Strength')], max_length=20, null=True),
        ),
    ]
