# Generated by Django 5.1.4 on 2025-03-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_booking_fitness_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fitness_goal',
        ),
    ]
